Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-06, with the labels that each got.

#801 fix: Javadoc method definition add modifier
  src/main/java/com/ly/doc/template/IJavadocDocTemplate.java
Labels: bug

#802 Optimize: Optimize the repetitive code in RPC and Javadoc document ge…
  src/main/java/com/ly/doc/model/RpcJavaMethod.java
  src/main/java/com/ly/doc/template/IDocBuildBaseTemplate.java
  src/main/java/com/ly/doc/template/IJavadocDocTemplate.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/IRpcDocTemplate.java
  src/main/java/com/ly/doc/template/JavadocDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
Labels: enhancement

#803 fix: Fix the bug where enum type parameter comments are missing in the query
  src/main/java/com/ly/doc/helper/FormDataBuildHelper.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/ParamUtil.java
  src/main/resources/template/css/AllInOne.css
Labels: bug

#805 fix: Generic replacement error causing parsing bug.
  src/main/java/com/ly/doc/utils/DocUtil.java
  src/test/java/com/ly/doc/util/DocUtilTest.java
Labels: bug

#806 fix: Fix the bug where the sequence number sorting is incorrect when using the `@order` tag.
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/IWebSocketTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/template/JavadocDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SolonDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SpringBootDocBuildTemplate.java
Labels: bug

#808 fix: Fix the issue where exported documents display incorrectly in tools like Postman when the content-type is form-data and urlencoded.
  README.md
  README_CN.md
  src/main/java/com/ly/doc/builder/PostmanJsonBuilder.java
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/OpenApiBuilder.java
  src/main/java/com/ly/doc/model/DocJavaMethod.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JavadocDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/ApiParamTreeUtil.java
  src/main/resources/template/debug-all.html
  src/main/resources/template/dubbo/DubboAllInOne.html
  src/main/resources/template/html/debug.html
  src/main/resources/template/javadoc/JavadocAllInOne.html
Labels: bug

#809 feat: Optimize the document generation template return interface definition to support future API interface error configuration additions.
  src/main/java/com/ly/doc/builder/AdocDocBuilder.java
  src/main/java/com/ly/doc/builder/ApiDocBuilder.java
  src/main/java/com/ly/doc/builder/DocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/HtmlApiDocBuilder.java
  src/main/java/com/ly/doc/builder/JMeterBuilder.java
  src/main/java/com/ly/doc/builder/PostmanJsonBuilder.java
  src/main/java/com/ly/doc/builder/TornaBuilder.java
  src/main/java/com/ly/doc/builder/WordDocBuilder.java
  src/main/java/com/ly/doc/builder/javadoc/JavadocDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/OpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/SwaggerBuilder.java
  src/main/java/com/ly/doc/builder/rpc/RpcDocBuilderTemplate.java
  src/main/java/com/ly/doc/constants/SpringMvcAnnotations.java
  src/main/java/com/ly/doc/model/ApiExceptionStatus.java
  src/main/java/com/ly/doc/model/ApiSchema.java
  src/main/java/com/ly/doc/model/annotation/ExceptionAdviceAnnotation.java
  src/main/java/com/ly/doc/model/annotation/FrameworkAnnotations.java
  src/main/java/com/ly/doc/template/IBaseDocBuildTemplate.java
  src/main/java/com/ly/doc/template/IDocBuildTemplate.java
  src/main/java/com/ly/doc/template/IJavadocDocTemplate.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/template/JavadocDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SolonDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SpringBootDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/OpenApiSchemaUtil.java
Labels: enhancement

#810 feat: Supports generating descriptions for OpenAPI HTTP error statuses like 404, 500, etc.
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/OpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/SwaggerBuilder.java
  src/main/java/com/ly/doc/constants/SpringMvcAnnotations.java
  src/main/java/com/ly/doc/model/ApiConfig.java
  src/main/java/com/ly/doc/model/ApiExceptionStatus.java
  src/main/java/com/ly/doc/model/ExceptionAdviceMethod.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SolonDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SpringBootDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/HttpStatusUtil.java
Labels: enhancement

#811 release: 3.0.5.
  pom.xml
  src/main/java/com/ly/doc/constants/SpringMvcAnnotations.java
  src/main/java/com/ly/doc/template/SpringBootDocBuildTemplate.java
Labels: documentation

#812 deps: bump gson,slf4j-api,beetl,common-util to latest version
  pom.xml
Labels: dependencies

#813 fix: rest api sort error
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
Labels: bug

#814 fix: Tree structure parsing bug
  src/main/java/com/ly/doc/helper/JsonBuildHelper.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/utils/DocUtil.java
  src/test/java/com/ly/doc/util/DocUtilTest.java
Labels: bug

#815 deps: Bump JQuery to 3.7.1, Highlight.js to v11.9.0
  src/main/resources/template/js/highlight.min.js
  src/main/resources/template/js/jquery.min.js
Labels: dependencies

#817 fix: Fix the issue where the generated OpenAPI is not sorted according to the specified order.
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/model/DocMapping.java
Labels: bug

#818 optimised: Optimise the duplicate code in the template builders
  src/main/java/com/ly/doc/builder/BaseDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/HtmlApiDocBuilder.java
  src/main/java/com/ly/doc/builder/javadoc/JavadocDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/javadoc/JavadocHtmlBuilder.java
  src/main/java/com/ly/doc/builder/rpc/RpcDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/rpc/RpcHtmlBuilder.java
Labels: enhancement

#827 fix: It is suspected that the curl request generated under a single file cannot obtain the header correctly. Currently, the debug execution is successful under multiple files, and the curl command generated by copying cannot be requested. Changing to double quotation marks is normal
  src/main/java/com/ly/doc/utils/CurlUtil.java
  src/test/java/com/ly/doc/util/CurlUtilTest.java
Labels: bug

#825 fix: :bug: Prevent EntryAnnotation from being inherited from parent classes and interfaces
  src/main/java/com/ly/doc/model/annotation/FrameworkAnnotations.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
Labels: bug

#829 fix: :bug: Fix display issues for Instant and EnumSet<?> types
  src/main/java/com/ly/doc/utils/DocClassUtil.java
  src/main/java/com/ly/doc/utils/DocUtil.java
  src/main/java/com/ly/doc/utils/JavaClassValidateUtil.java
Labels: bug
