Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-09, with the labels that each got.

#905 ci: :construction_worker: run `TornaApiTest` in CI workflow
  .github/workflows/build-and-run-example-project.yml
Labels: ci

#910 feat: Fix the issue where the JsonValue annotation cannot be used on an enum.
  pom.xml
  src/main/java/com/ly/doc/helper/FormDataBuildHelper.java
  src/main/java/com/ly/doc/helper/JsonBuildHelper.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
  src/main/java/com/ly/doc/utils/ParamUtil.java
Labels: bug

#911 feat: Enum in the form skips parsing of JsonValue annotation.
  Makefile
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
Labels: bug

#912 feat: Modify the contact information in the Chinese README
  README_CN.md
  images/WeChat-Official-Account.png
  images/smart-doc-qq2.jpeg
Labels: documentation

#913 feat: Modify the contact information in the English README
  README.md
  README_CN.md
  src/main/resources/template/dubbo/DubboAllInOne.md
  src/main/resources/template/javadoc/JavadocAllInOne.md
  src/main/resources/template/websocket/WebSocketAllOne.md
Labels: documentation

#916 feat(enum): Support `@JsonValue` annotation on enum fields
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
Labels: bug

#917 Fix resolve stack overflow from duplicate ApiParam IDs with enum key Maps
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
Labels: bug

#919 feat: bump common-util to 2.2.6
  pom.xml
Labels: dependencies

#920 feat: Support Postman collection grouping
  src/main/java/com/ly/doc/builder/PostmanJsonBuilder.java
Labels: enhancement
