Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-02, with the labels that each got.

#724 fix #722, Ignore NoClassDefFoundError
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
Labels: enhancement

#727 update CHANGELOG.md for 3.0.2
  CHANGELOG.md
Labels: documentation

#728 Fix the bug that prevents parsing when using an inner enum class as a…
  src/main/java/com/ly/doc/template/IBaseDocBuildTemplate.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
  src/main/java/com/ly/doc/utils/JsonUtil.java
  src/test/java/com/ly/doc/util/JsonUtilTest.java
Labels: bug

#729 Fix JAX-RS documentation generation bug.
  src/main/java/com/ly/doc/helper/DocBuildHelper.java
  src/main/java/com/ly/doc/model/DocJavaParameter.java
  src/main/java/com/ly/doc/model/dependency/DependencyTree.java
  src/main/java/com/ly/doc/template/IBaseDocBuildTemplate.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JaxrsDocBuildTemplate.java
Labels: bug

#730 Optimize constant retrieval
  src/main/java/com/ly/doc/handler/IHeaderHandler.java
  src/main/java/com/ly/doc/handler/JaxrsHeaderHandler.java
  src/main/java/com/ly/doc/handler/JaxrsPathHandler.java
  src/main/java/com/ly/doc/handler/SolonRequestMappingHandler.java
  src/main/java/com/ly/doc/handler/SpringMVCRequestMappingHandler.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JaxrsDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/DocUtil.java
  src/main/java/com/ly/doc/utils/JavaFieldUtil.java
Labels: enhancement

#731 format code
  CHANGELOG.md
  src/main/java/com/ly/doc/handler/JaxrsHeaderHandler.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JaxrsDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/JavaFieldUtil.java
Labels: documentation

#738 refactor: :recycle: rename param type constants and format code
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/OpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/SwaggerBuilder.java
  src/main/java/com/ly/doc/constants/DocGlobalConstants.java
  src/main/java/com/ly/doc/helper/FormDataBuildHelper.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/model/ApiReqParam.java
  src/main/java/com/ly/doc/model/CustomField.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JaxrsDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/ParamUtil.java
  src/main/java/com/ly/doc/utils/TornaUtil.java
Labels: enhancement

#744 fix: change log
  CHANGELOG.md
Labels: documentation
