Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-08, with the labels that each got.

#872 ci: :construction_worker: Add artifact upload steps for documentation
  .github/workflows/build-and-run-example-project.yml
Labels: ci

#870 feat: ✨ Add support for Map with enum type keys
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/OpenApiBuilder.java
  src/main/java/com/ly/doc/builder/openapi/SwaggerBuilder.java
  src/main/java/com/ly/doc/helper/JsonBuildHelper.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
Labels: enhancement

#883 feat(github-actions): set up weekly dependency updates
  .github/dependabot.yml
Labels: ci

#882 Added support for message and response parameters
  README.md
  src/main/java/com/ly/doc/builder/websocket/WebSocketDocBuilderTemplate.java
  src/main/java/com/ly/doc/constants/DocAnnotationConstants.java
  src/main/java/com/ly/doc/constants/TemplateVariable.java
  src/main/java/com/ly/doc/handler/IWebSocketRequestHandler.java
  src/main/java/com/ly/doc/helper/DocBuildHelper.java
  src/main/java/com/ly/doc/model/WebSocketDoc.java
  src/main/java/com/ly/doc/model/request/ServerEndpoint.java
  src/main/java/com/ly/doc/template/IWebSocketDocBuildTemplate.java
  src/main/java/com/ly/doc/template/IWebSocketTemplate.java
  src/main/resources/template/websocket/WebSocket.adoc
  src/main/resources/template/websocket/WebSocket.md
  src/main/resources/template/websocket/WebSocketAllInOne.adoc
  src/main/resources/template/websocket/WebSocketAllInOne.html
  src/main/resources/template/websocket/WebSocketAllOne.md
Labels: enhancement

#892 Ensure Java format validation reports failure explicitly
  .github/workflows/spring-javaformat-validate.yml
Labels: ci

#893 feat: release 3.0.7
  pom.xml
Labels: release

#896 ignore JGit and Data Faker dependencies
  .github/dependabot.yml
Labels: ci

#897 Corrected incorrect use of 'version' to 'versions' in Dependabot config
  .github/dependabot.yml
Labels: ci

#902 Handle single @ServerEndpoint property values correctly
  src/main/java/com/ly/doc/handler/IRequestMappingHandler.java
  src/main/java/com/ly/doc/handler/IWebSocketRequestHandler.java
  src/main/java/com/ly/doc/model/ApiMethodDoc.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
Labels: bug
