Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-07, with the labels that each got.

#841 fix: :bug: ensure non-null collections for API schema properties
  src/main/java/com/ly/doc/model/ApiSchema.java
  src/main/java/com/ly/doc/template/IDocBuildTemplate.java
Labels: bug

#839 refactor(build-template): ♻️ utilize ServiceLoader for dynamic loading
  src/main/java/com/ly/doc/builder/AdocDocBuilder.java
  src/main/java/com/ly/doc/builder/ApiDocBuilder.java
  src/main/java/com/ly/doc/builder/DocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/HtmlApiDocBuilder.java
  src/main/java/com/ly/doc/builder/JMeterBuilder.java
  src/main/java/com/ly/doc/builder/PostmanJsonBuilder.java
  src/main/java/com/ly/doc/builder/TornaBuilder.java
  src/main/java/com/ly/doc/builder/WordDocBuilder.java
  src/main/java/com/ly/doc/builder/javadoc/JavadocDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/builder/rpc/RpcDocBuilderTemplate.java
  src/main/java/com/ly/doc/builder/websocket/WebSocketMarkdownBuilder.java
  src/main/java/com/ly/doc/constants/FrameworkEnum.java
  src/main/java/com/ly/doc/factory/BuildTemplateFactory.java
  src/main/java/com/ly/doc/template/IDocBuildBaseTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/template/JavadocDocBuildTemplate.java
  src/main/java/com/ly/doc/template/RpcDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SolonDocBuildTemplate.java
  src/main/java/com/ly/doc/template/SpringBootDocBuildTemplate.java
  src/main/resources/META-INF/services/com.ly.doc.template.IDocBuildTemplate
  src/main/resources/META-INF/services/com.ly.doc.template.IWebSocketDocBuildTemplate
Labels: enhancement

#843 feat: add style check
  .github/workflows/maven.yml
Labels: running

#844 feat: add google_checks.xml
  .github/workflows/maven.yml
  checkstyle/google_checks.xml
Labels: enhancement

#845 feat: release 3.0.6
  .github/workflows/maven.yml
  Makefile
  pom.xml
Labels: documentation

#860 docs: update README
  README.md
  README_CN.md
Labels: documentation

#862 feat: disable blank issue creation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation
