Repository TongchengOpenSource/smart-doc, pull requests merged in 2024-12, with the labels that each got.

#985 feat(doc): 'html', 'adoc', 'doc' should support 'Example' just as 'markdown'
  src/main/resources/template/AllInOne.adoc
  src/main/resources/template/AllInOne.html
  src/main/resources/template/ApiDoc.adoc
  src/main/resources/template/html/index.html
  src/main/resources/template/word/AllInOneWordTemplate.xml
  src/main/resources/template/word/index.xml
Labels: enhancement

#987 feat: bump qdox to 2.0.3.5 and support jdk17 text block
  pom.xml
Labels: enhancement

#992 feat(html): html template automatic compress
  src/main/java/com/ly/doc/utils/BeetlTemplateUtil.java
  src/main/java/com/ly/doc/utils/HtmlCompressorUtil.java
  src/main/resources/template/debug-all.html
  src/main/resources/template/dubbo/DubboAllInOne.html
  src/main/resources/template/grpc/GrpcAllInOne.html
  src/main/resources/template/html/debug.html
  src/main/resources/template/javadoc/JavadocAllInOne.html
  src/main/resources/template/websocket/WebSocketAllInOne.html
Labels: enhancement

#993 feat: add star History
  README.md
  README_CN.md
Labels: documentation

#996 fix: 🐛 Enhance enum dictionary generation and improve enum class resolution
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
  src/main/java/com/ly/doc/utils/JavaClassUtil.java
  src/main/java/com/ly/doc/utils/ParamUtil.java
  src/main/java/com/ly/doc/utils/RequestExampleUtil.java
Labels: bug

#1005 fix(map): Fix the response result is Map<Enum, Value> is not parsed correctly
  src/main/java/com/ly/doc/builder/ProjectDocConfigBuilder.java
  src/main/java/com/ly/doc/helper/ParamsBuildHelper.java
Labels: bug

#1006 ci: :construction_worker: update PR comment template
  .github/workflows/pr-comment.yml
Labels: ci
