Repository TongchengOpenSource/smart-doc, pull requests merged in 2025-01, with the labels that each got.

#1014 fix dubbo word template bug
  src/main/resources/template/dubbo/DubboAllInOneWordTemplate.xml
Labels: bug

#1016 feat: bump common-util to 2.2.9
  pom.xml
Labels: dependencies

#1019 refactor(doc): :art: improve API documentation generation and enforce strict `Javadoc` validation
  pom.xml
  src/main/java/com/ly/doc/builder/IRpcDocBuilderTemplate.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
Labels: documentation
