Repository TongchengOpenSource/smart-doc, pull requests merged in 2025-05, with the labels that each got.

#1054 docs: :memo: add contributing guidelines in English and Chinese
  CONTRIBUTING.md
  CONTRIBUTING_CN.md
Labels: documentation

#1057 Fix issue 1046
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/template/IRestDocTemplate.java
  src/main/java/com/ly/doc/template/JAXRSDocBuildTemplate.java
  src/main/java/com/ly/doc/utils/DocUtil.java
Labels: bug

#1060 feat(openapi): :sparkles: add support for generating tags by description or package name
  src/main/java/com/ly/doc/builder/openapi/AbstractOpenApiBuilder.java
  src/main/java/com/ly/doc/constants/OpenApiTagNameTypeEnum.java
  src/main/java/com/ly/doc/model/ApiConfig.java
  src/main/java/com/ly/doc/model/DocMapping.java
  src/main/java/com/ly/doc/model/openapi/OpenApiTag.java
Labels: enhancement

#1062 docs: :memo: update contribution guidelines and PR review process
  .github/workflows/pr-comment.yml
  CONTRIBUTING.md
  CONTRIBUTING_CN.md
Labels: documentation
